adv:	adv_io.c simple_remarking.c sudoku_advanced.c unique_candidates.c subsets.c validation.c x_wing.c sword_fish.c shared_subgroup.c
	gcc adv_io.c simple_remarking.c sudoku_advanced.c unique_candidates.c subsets.c validation.c x_wing.c sword_fish.c shared_subgroup.c -o adv

adv_optimized:	adv_io.c simple_remarking.c sudoku_advanced.c unique_candidates.c subsets.c validation.c x_wing.c sword_fish.c shared_subgroup.c
	gcc adv_io.c simple_remarking.c sudoku_advanced.c unique_candidates.c subsets.c validation.c x_wing.c sword_fish.c shared_subgroup.c -o adv_optimized -O2

clean:
	rm -f adv
	rm -f adv_optimized
